# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Category.create(name: 'Hotelaria')
Category.create(name: 'Lazer')
Category.create(name: 'Parques')
Category.create(name: 'Evento (local fechado)')
Category.create(name: 'Atrações (local aberto)')
Category.create(name: 'Fora de Estrada 4x4')
Category.create(name: 'Águas Brancas')
Category.create(name: 'Mar')
Category.create(name: 'Ecoturismo')
Category.create(name: 'Voo Livre')
Category.create(name: 'Embarcação')

SubCategory.create(name: 'Hotel', category: Category.find_by(name: 'Hotelaria'))
SubCategory.create(name: 'Pousada', category: Category.find_by(name: 'Hotelaria'))
SubCategory.create(name: 'Camping', category: Category.find_by(name: 'Hotelaria'))
SubCategory.create(name: 'Trenzinho', category: Category.find_by(name: 'Lazer'))
SubCategory.create(name: 'Ultraleve', category: Category.find_by(name: 'Lazer'))
SubCategory.create(name: 'Helicóptero', category: Category.find_by(name: 'Lazer'))
SubCategory.create(name: 'Bicicleta', category: Category.find_by(name: 'Lazer'))
SubCategory.create(name: 'Piscina', category: Category.find_by(name: 'Lazer'))
SubCategory.create(name: 'Acantonamento', category: Category.find_by(name: 'Lazer'))
SubCategory.create(name: 'Skate', category: Category.find_by(name: 'Lazer'))
SubCategory.create(name: 'Pipa', category: Category.find_by(name: 'Lazer'))
SubCategory.create(name: 'Trio Elétrico', category: Category.find_by(name: 'Lazer'))
SubCategory.create(name: 'Teleférico', category: Category.find_by(name: 'Lazer'))
SubCategory.create(name: 'Zoológico', category: Category.find_by(name: 'Lazer'))
SubCategory.create(name: 'Praça Pública', category: Category.find_by(name: 'Lazer'))
SubCategory.create(name: 'Rio / Represa / Lago', category: Category.find_by(name: 'Lazer'))
SubCategory.create(name: 'Praia', category: Category.find_by(name: 'Lazer'))
SubCategory.create(name: 'Lazer (Outros)', category: Category.find_by(name: 'Lazer'))
SubCategory.create(name: 'Parque de Diversões', category: Category.find_by(name: 'Parques'))
SubCategory.create(name: 'Parque Aquático', category: Category.find_by(name: 'Parques'))
SubCategory.create(name: 'Parque Temático', category: Category.find_by(name: 'Parques'))
SubCategory.create(name: 'Parquinho Infantil', category: Category.find_by(name: 'Parques'))
SubCategory.create(name: 'Parque Público', category: Category.find_by(name: 'Parques'))
SubCategory.create(name: 'Parques (Outros)', category: Category.find_by(name: 'Parques'))
SubCategory.create(name: 'Buffet', category: Category.find_by(name: 'Evento (local fechado)'))
SubCategory.create(name: 'Restaurante', category: Category.find_by(name: 'Evento (local fechado)'))
SubCategory.create(name: 'Eventos (Outros)', category: Category.find_by(name: 'Evento (local fechado)'))
SubCategory.create(name: 'Espetáculo', category: Category.find_by(name: 'Atrações (local aberto)'))
SubCategory.create(name: 'Exposição', category: Category.find_by(name: 'Atrações (local aberto)'))
SubCategory.create(name: 'Monumento Turístico', category: Category.find_by(name: 'Atrações (local aberto)'))
SubCategory.create(name: 'Campo de Futebol', category: Category.find_by(name: 'Atrações (local aberto)'))
SubCategory.create(name: 'Atrações (Outros)', category: Category.find_by(name: 'Atrações (local aberto)'))
SubCategory.create(name: 'Buggy', category: Category.find_by(name: 'Fora de Estrada 4x4'))
SubCategory.create(name: 'Quadriciclo', category: Category.find_by(name: 'Fora de Estrada 4x4'))
SubCategory.create(name: 'Jipe', category: Category.find_by(name: 'Fora de Estrada 4x4'))
SubCategory.create(name: 'Fora de Estrada 4x4 (Outros)', category: Category.find_by(name: 'Fora de Estrada 4x4'))
SubCategory.create(name: 'Rafting', category: Category.find_by(name: 'Aventura em Águas Brancas'))
SubCategory.create(name: 'Boia Cross', category: Category.find_by(name: 'Aventura em Águas Brancas'))
SubCategory.create(name: 'Caiaque', category: Category.find_by(name: 'Aventura em Águas Brancas'))
SubCategory.create(name: 'Águas Brancas (Outros)', category: Category.find_by(name: 'Aventura em Águas Brancas'))
SubCategory.create(name: 'Mergulho', category: Category.find_by(name: ' Mar'))
SubCategory.create(name: 'Parasail', category: Category.find_by(name: ' Mar'))
SubCategory.create(name: 'Paraglider', category: Category.find_by(name: ' Mar'))
SubCategory.create(name: 'Wind surf', category: Category.find_by(name: ' Mar'))
SubCategory.create(name: 'Kitesurfe', category: Category.find_by(name: ' Mar'))
SubCategory.create(name: 'Banana boat', category: Category.find_by(name: ' Mar'))
SubCategory.create(name: 'Stand Up Paddle', category: Category.find_by(name: ' Mar'))
SubCategory.create(name: 'Surf', category: Category.find_by(name: ' Mar'))
SubCategory.create(name: 'Mar (Outros)', category: Category.find_by(name: ' Mar'))
SubCategory.create(name: 'Cicloturismo', category: Category.find_by(name: 'Ecoturismo'))
SubCategory.create(name: 'Rapel / Canionismo', category: Category.find_by(name: 'Ecoturismo'))
SubCategory.create(name: 'Espeleoturismo', category: Category.find_by(name: 'Ecoturismo'))
SubCategory.create(name: 'Escalada', category: Category.find_by(name: 'Ecoturismo'))
SubCategory.create(name: 'Arvorismo', category: Category.find_by(name: 'Ecoturismo'))
SubCategory.create(name: 'Tirolesa', category: Category.find_by(name: 'Ecoturismo'))
SubCategory.create(name: 'Montanhismo', category: Category.find_by(name: 'Ecoturismo'))
SubCategory.create(name: 'Cavalo', category: Category.find_by(name: 'Ecoturismo'))
SubCategory.create(name: 'Acampamento', category: Category.find_by(name: 'Ecoturismo'))
SubCategory.create(name: 'Caminhada', category: Category.find_by(name: 'Ecoturismo'))
SubCategory.create(name: 'Trilha', category: Category.find_by(name: 'Ecoturismo'))
SubCategory.create(name: 'Cachoeira', category: Category.find_by(name: 'Ecoturismo'))
SubCategory.create(name: 'Ecoturismo (Outros)', category: Category.find_by(name: 'Ecoturismo'))
SubCategory.create(name: 'Parapente / Paraglider', category: Category.find_by(name: 'Voo Livre'))
SubCategory.create(name: 'Asa Delta', category: Category.find_by(name: 'Voo Livre'))
SubCategory.create(name: 'Balonismo', category: Category.find_by(name: 'Voo Livre'))
SubCategory.create(name: 'Voo Livre (Outros)', category: Category.find_by(name: 'Voo Livre'))
SubCategory.create(name: 'Escuna', category: Category.find_by(name: 'Embarcação'))
SubCategory.create(name: 'Lancha', category: Category.find_by(name: 'Embarcação'))
SubCategory.create(name: 'Navio', category: Category.find_by(name: 'Embarcação'))
SubCategory.create(name: 'Catamarã', category: Category.find_by(name: 'Embarcação'))
SubCategory.create(name: 'Veleiro', category: Category.find_by(name: 'Embarcação'))
SubCategory.create(name: 'Jangada', category: Category.find_by(name: 'Embarcação'))
SubCategory.create(name: 'Bote', category: Category.find_by(name: 'Embarcação'))
SubCategory.create(name: 'Jet Ski', category: Category.find_by(name: 'Embarcação'))
SubCategory.create(name: 'Embarcação (Outros)', category: Category.find_by(name: 'Embarcação'))

Chapter.create(name: 'Cicloturismo')
Chapter.create(name: 'Piscina')
Chapter.create(name: 'Trilha e atividades autoguiadas')
Chapter.create(name: 'Turismo de Aventura Contratado')
Chapter.create(name: 'Hotelaria')
Chapter.create(name: 'Embarcações')

Purpose.create(name: 'Turismo de Atrações')
Purpose.create(name: 'Turismo de Aventura')
Purpose.create(name: 'Turismo de Eventos')
Purpose.create(name: 'Turismo de Lazer')
Purpose.create(name: 'Turismo Ecológico')
Purpose.create(name: 'Turismo Náutico')

OccurrenceFactor.create(name: 'Terra')
OccurrenceFactor.create(name: 'Ar')
OccurrenceFactor.create(name: 'Água')
